# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic settings
title: "Cristian Inzunza D. – Numerical Analysis & PDEs"
email: cr.inzunza.d@gmail.com
description: >-
  Postdoctoral researcher in numerical analysis of nonlinear and coupled PDEs. Focused on mixed finite element methods in Banach spaces.
baseurl: "" # leave empty for user.github.io
url: "https://crinzunza.github.io"
github_username: Crinzunza

# Author profile
author:
  name: "Cristian Inzunza D."
  avatar: "/images/profile.png"
  bio: >
    Postdoctoral researcher at the Center for Mathematical Modeling (CMM), Universidad de Chile, and collaborator at GIANuC² – Universidad Católica de la Santísima Concepción.
  location: Chile
  email: cr.inzunza.d@gmail.com
  orcid: https://orcid.org/0000-0003-2959-6779
  googlescholar: https://scholar.google.com/citations?user=PS_CX0AAAAAJ
  github: Crinzunza
  linkedin:
  twitter:
  mastodon:
  youtube:

# Appearance
theme: minimal
logo: "/images/profile.png"
show_downloads: false

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

paginate: 5
paginate_path: "/page:num/"

